---
- name: Collection Test Wrapper
  hosts: localhost
  connection: local
  gather_facts: false

  # CRITICAL: This adds the current folder structure to the path
  # effectively "installing" the collection for this run.
  collections:
    - osac.demo

  tasks:
    - name: Import the role from the collection
      import_role:
        name: osac.demo.shadow_test
      vars:
        my_name: "Sandbox User"